### ISSUE TITLE
Implement concurrency for single file WebDAV upload

### ISSUE THREAD

**Issue by jhdscript** [retroplasma/binsync#1]
Hello, first thanx for your project it s amazing.

But i have a speed issue when posting articles.

With nyuu i reached 20Mb/s whereas the lib u use never exceed 1mb/s

Have you a tips for improve the speed?

Regards

**Comment by retroplasma** [comment]
It might be due to limited concurrency if you are posting a single file.

Concurrency isn't implemented for single file WebDAV uploads at the moment; it only uses one connection at a time unless you upload multiple files in parallel. It's implemented in Binsync.Core so it's doable but I can't promise that I'll have time to look into it soon.

[Here](https://github.com/retroplasma/binsync/blob/cbc02d8c2f4d8683c86471008b8581863b80f2cc/src/Binsync.Util/BinsyncStream2.cs) is the upload stream implementation that is used with WebDAV.  It should be doable by blocking after multiple segments instead of one. (Kinda inverse look-ahead similar to the [download stream](https://github.com/retroplasma/binsync/blob/cbc02d8c2f4d8683c86471008b8581863b80f2cc/src/Binsync.Util/BinsyncStream.cs))
